### ISSUE TITLE
Do you have a portable version that doesn't require installing?

### ISSUE THREAD

**Issue by DumbJoe** [dxgldotorg/dxgl#12]
As I can't seem to install mine since it hangs at this bit:
![image](https://user-images.githubusercontent.com/36319788/195705899-5b01bcb2-ba0b-4c32-ad7c-878f78be054c.png)
so thought maybe portable method might fix this for me here.

**Comment by dxgldotorg** [comment]
Currently, loose binaries are not distributed, however you can manually copy dxglcfg.exe and ddraw.dll from an existing installation.

**Comment by DumbJoe** [comment]
> however you can manually copy dxglcfg.exe and ddraw.dll from an existing installation.

Thanks, very helpful...

**Comment by oddMLan** [comment]
I'm having the same issue with the installer being stuck there. Even copying the DLL and config exe doesn't work. Config just hangs.

Windows 10 Pro 21H1

**Comment by BlueStarBRS** [comment]
same here i only want this here forone game and not for my complete windows

**Comment by dxgldotorg** [comment]
Hi.  Sorry for the long delay, I'm making the finishing touches on the next version which will include a portable option for installation.

**Comment by dxgldotorg** [comment]
DXGL 0.5.21 is released, with a new Portable installation mode.
