### ISSUE TITLE
DXGL doesn't prevent screensaver (or screen saver)

### ISSUE THREAD

**Issue by jodo13** [dxgldotorg/dxgl#19]
OS: Windows 7 SP1
DXGL: 0.5.20
Target software: Nester NES emulator (https://web.archive.org/web/20040717084236/http://nester.dranalli.com/)

I haven't tested with other software as I'm using DXGL explicitly because is the only one that gave me the best results with this OLD directdraw application, and to be precise, the only that prevents this old software to have swap colors (256 colors app) on fullscreen.

I know that that emulator is old, but, isn't DXGL's purpose to run old DD software, after all? ;)

Anyway, it doesn't matter if I use an "exclusive fullscreen" mode, or any other, but after the 5 minutes I have it setup, the screensaver is triggered and not prevented.

I haven't seen any other option that could help.

In my very special case, I don't use the keyboard or mouse with this emulator and the gamepad wrapper (RockFire gameport>USB converter), also, can't be setup to avoid screensaver triggering.

But I guess that is not a concern, as video players, as Media Player Classic, don't have any kind of input and they prevent themselves the trigger of the screensaver, so I guess, and this is my point, maybe it can be done as well on DXGL.

I hope this could be fixed through DXGL, if not, thanks for reading, at least :-)

**Comment by jodo13** [comment]
I forgot to test and mention that the emulator itself, without DXGL help to display colors correctly, prevents effectively the screensaver.

As DXGL is kind of a video wrapping, as I told earlier, I guess this should get fixed on DXGL

**Comment by dxgldotorg** [comment]
This will be part of the 0.5.21 maintenance release.

**Comment by jodo13** [comment]
Nice, thanks for you work .

I'll have to have a look when it releases :)

**Comment by dxgldotorg** [comment]
Probably before the end of the year.

**Comment by dxgldotorg** [comment]
Installer has now been published.

**Comment by jodo13** [comment]
Looks like the fix works :)

I left The Legend of Zelda demo a few minutes, without touching anything and prevented the screensaver and the monitor to go to sleep.


If you don't mind, and sorry the off-topic and I should have asked as an issue earlier (happened on earlier version) but, is it normal that from switching from fullscreen to window the titlebar disappears? Maybe is related to this emulator only, but, just asking.

Also, is it normal that the mouse pointer, when moved (happened on earlier version as well) is being seen?

It is not annoying to the point to open an issue, I mean if it is normal, it is normal. Just asking. Maybe you consider an issue and you consider it needs a fix, but, as I said, just asking to know :)

**Comment by dxgldotorg** [comment]
Go ahead and open issues.  It will be a longer term change as I am trying to move away from the 0.5.x branch.
