### ISSUE TITLE
Will this ever support DirectX 9, 10, etc..?

### ISSUE THREAD

**Issue by AnErrupTion** [dxgldotorg/dxgl#6]
Hello!

First of all, I love that this project exists (hopefully it can "compete" against DXVK soon) and the efforts you're putting into it. Now, my main question is: will this project ever support DirectX 9+? And if yes, is there an ETA for that or not?

The reason for that is that my GPU doesn't support Vulkan and I'm on Linux, so I can't play pretty much any game that doesn't natively support OpenGL. And this project only supporting DirectX 7 it seems like, there's not much games that can be played apart from the older ones.

**Comment by Faalagorn** [comment]
Kinda offtopic, but if your GPU doesn't support Vulkan, then I guess your best bet would be either Gallium Nine for DX9 or WineD3D for DX10-11. Out of curiosity though, what GPU do you have?

**Comment by AnErrupTion** [comment]
I have a Fermi GPU.

**Comment by Faalagorn** [comment]
> I have a Fermi GPU.

Ah, I forgot about those… then indeed Gallium Nine is out of question sadly :(
